[workspace]
members = ["programs/token_2022", "programs/x402-on-demand"]

[features]
seeds = false
skip-lint = true

[programs.localnet]
token_2022 = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
attention_oracle_program = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
x402_on_demand = "7buCx5353jtT5rsmNr8U6Xe7a41sL1pmkZwzYCCSAmKF"

[programs.devnet]
token_2022 = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
attention_oracle_program = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
x402_on_demand = "7buCx5353jtT5rsmNr8U6Xe7a41sL1pmkZwzYCCSAmKF"

[programs.mainnet]
token_2022 = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
attention_oracle_program = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
x402_on_demand = "7buCx5353jtT5rsmNr8U6Xe7a41sL1pmkZwzYCCSAmKF"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[verify]
mountPath = "."
buildCommand = ["cargo", "build-sbf"]
