[workspace]
members = ["programs/token_2022", "programs/attention_oracle_program"]

[features]
seeds = false
skip-lint = true

[programs.localnet]
token_2022 = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
attention_oracle_program = "Attn1111111111111111111111111111111111111111"

[programs.mainnet]
token_2022 = "GnGzNdsQMxMpJfMeqnkGPsvHm8kwaDidiKjNU2dCVZop"
attention_oracle_program = "Attn1111111111111111111111111111111111111111"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[verify]
mountPath = "programs/token_2022"
buildCommand = ["cargo", "build-sbf"]
