[workspace]
members = [
  "programs/token_2022",
  "programs/x402-on-demand",]
exclude = [
  "programs/attention_oracle_program"
]
resolver = "2"
[profile.release]
opt-level = "z"
overflow-checks = true
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
